#运行环境
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build:min
  - npm run build:web:min
  - npm run build:appeg:min
  - npm run build:webeg:min

branches:
  only:
    - master