#运行环境
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  # - npm run dist // parcel-plugin-eslint bug
  - npm run webbuild

branches:
  only:
    - master